export const ADD_INGRIEDENT = 'ADD_INGRIEDENT';
export const REMOVE_INGRIEDENT = 'REMOVE_INGRIEDENT';
export const SET_INGRIEDENT = 'SET_INGRIEDENT';
export const FETCH_INGRIEDENT_FAILED = 'FETCH_INGRIEDENT_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const INIT_PURCHASED = 'INIT_PURCHASED';
export const INIT_ORDERS = 'INIT_ORDERS';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const REDIRECT_AUTH_PATH = 'REDIRECT_AUTH_PATH';